service: pdf-cropper
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  httpApi:
    id: emc8aum0wj
  memorySize: 256
  timeout: 15
  tags:
    Owner: choshsh
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
        file: Dockerfile

functions:
  pdfcrop:
    image: appimage
    events:
      - httpApi:
          path: /pdfcrop
          method: post